// content.js
export const QUESTIONS = {
    "Spark Questions": [
      "What’s the most unusual food you’ve ever tried?",
      "If you could swap lives with a celebrity for one day, who would it be?",
      "What’s your guilty pleasure TV show or movie?",
      "What’s the funniest thing you believed as a kid?",
      "If you had a theme song that played when you walked into a room, what would it be?",
      "What’s the weirdest talent you have?",
      "If you had to eat one meal for the rest of your life, what would it be?",
      "What’s the most spontaneous thing you’ve ever done?",
      "Which fictional character do you relate to the most?",
      "What’s your go-to karaoke song?",
      "What’s the worst haircut you’ve ever had?",
      "Would you rather explore space or the deep ocean?",
      "What’s the strangest thing you’ve ever collected?",
      "What’s your “happy” food?",
      "If you had a time machine, what’s the first year you’d visit?",
      "What’s your dream vacation spot?",
      "What’s your most used emoji?",
      "Do you prefer sunrise or sunset?",
      "What’s your “comfort” movie?",
      "If you could instantly learn a new skill, what would it be?",
      "What’s the funniest prank you’ve ever pulled or had pulled on you?",
      "What’s your biggest pet peeve?",
      "Coffee, tea, or neither?",
      "If you could only wear one color forever, what would it be?",
      "What’s the strangest dream you’ve had?"
    ],
    "Mirror Moments": [
      "What’s the best advice you’ve ever received?",
      "What life event shaped you the most?",
      "Who’s been the biggest influence in your life?",
      "What’s your proudest accomplishment?",
      "What do you think your younger self would be proud of you for?",
      "What’s something you’re still learning about yourself?",
      "What’s the hardest decision you’ve had to make?",
      "What’s a belief you had 5 years ago that’s changed?",
      "What do you value most in a friendship?",
      "When do you feel most at peace?",
      "What’s the scariest thing you’ve overcome?",
      "What’s your definition of love?",
      "What’s one fear you’d like to conquer?",
      "What’s your most sentimental possession?",
      "When do you feel the most alive?",
      "What habit are you most proud of breaking?",
      "Who do you admire most?",
      "What do you want your legacy to be?",
      "What’s a lesson you learned the hard way?",
      "What makes you feel truly appreciated?",
      "What’s a dream you’ve given up on (or still holding onto)?",
      "If money wasn’t an issue, what would you be doing right now?",
      "What do you want more of in your life?",
      "What do you wish people understood about you?",
      "What’s the most important value you live by?"
    ],
    "Playful Sparks": [
      "Aliens land tomorrow — what’s the first thing you ask them?",
      "What’s the most ridiculous fashion trend you’ve followed?",
      "If you could live inside any movie, which would it be?",
      "What’s your spirit animal?",
      "What’s your zombie apocalypse survival plan?",
      "If you had to create a holiday, what would it celebrate?",
      "Which superhero/villain do you think you’re most like?",
      "What’s the weirdest food combo you secretly love?",
      "What’s your karaoke strategy: serious or silly?",
      "If you could switch bodies with someone for a day, who would it be?",
      "What’s your guilty pleasure snack?",
      "Would you rather be able to fly or be invisible?",
      "If you were a flavor, what would it be?",
      "What’s the weirdest nickname you’ve had?",
      "Which conspiracy theory do you secretly wonder about?",
      "What’s the strangest superstition you’ve heard of?",
      "If animals could talk, which would be the rudest?",
      "What’s the most embarrassing thing you’ve done in public?",
      "Which emoji describes you best today?",
      "What’s the last thing that made you laugh until you cried?",
      "Do you believe in luck?",
      "If you could instantly master a language, which one would it be?",
      "What’s your guilty pleasure music artist?",
      "What’s your weirdest “shower thought”?",
      "If your life was a book, what would the title be?"
    ],
    "Bond Builders": [
      "What’s your love language?",
      "What’s your favorite memory with friends?",
      "What makes you feel most connected to others?",
      "What’s the most romantic thing you’ve ever done (or had done for you)?",
      "What’s your favorite “bonding” activity?",
      "What’s the best compliment you’ve ever gotten?",
      "What’s your biggest relationship lesson so far?",
      "How do you like to celebrate milestones?",
      "What’s your friendship “green flag”?",
      "What kind of people inspire you most?",
      "What’s your favorite family tradition?",
      "What’s your biggest “ick” in relationships?",
      "Who’s your role model for love/friendship?",
      "What’s your dream adventure with friends/partner?",
      "What do you look for in a teammate?",
      "What’s your go-to way to cheer someone up?",
      "What’s your favorite bonding memory at work/school?",
      "What’s your perfect first date idea?",
      "How do you show appreciation for people in your life?",
      "What’s a “dealbreaker” for you in relationships/friendships?",
      "What’s your favorite kind of surprise?",
      "How do you handle conflict in relationships?",
      "What does “quality time” mean to you?",
      "What makes someone unforgettable to you?",
      "What’s your idea of the perfect day with someone?"
    ],
  };
  
  export const MISSIONS = {
    "Adventure Sparks": [
      "Go to the tallest building in your city and take a picture of the view.",
      "Visit a local museum or gallery and find your favorite piece.",
      "Go to a random bus stop, take the bus, and get off after 5 stops — explore.",
      "Find a hidden gem restaurant with fewer than 20 reviews online.",
      "Go to a park and build a mini fort out of natural materials.",
      "Visit a new neighborhood you’ve never walked through.",
      "Explore a thrift store and each pick one quirky item for the other.",
      "Go geocaching together.",
      "Find a mural or graffiti wall and take a creative photo in front of it.",
      "Go to a pet store and play with the animals.",
      "Take a spontaneous day trip within 2 hours of your city.",
      "Go on a “sunrise mission” — watch the sunrise from a scenic spot.",
      "Visit the oldest building in your city.",
      "Go to a farmer’s market and pick one food neither of you has tried.",
      "Hunt for a “weird landmark” in your city and take a picture.",
      "Find the quietest spot in your city and just sit there.",
      "Go to a bookstore, pick a book for each other, and exchange.",
      "Explore a local flea market together.",
      "Go to a playground and act like kids again.",
      "Find a place that sells the weirdest flavored drink and try it.",
      "Go stargazing away from city lights.",
      "Try a food truck you’ve never eaten from before.",
      "Find a hidden staircase, alley, or path in your city.",
      "Visit a historical monument near you.",
      "Do a “random spin” on Google Maps, and go wherever it lands nearby."
    ],
    "Creative Charms": [
      "Buy a disposable camera and document your day together.",
      "Write and perform a silly poem about each other.",
      "Draw portraits of each other (no matter the skill level).",
      "Make up a 2-minute comedy skit and act it out.",
      "Write a 6-line rap about your day.",
      "Do a chalk-art session on the sidewalk.",
      "Create a TikTok or reel about your adventure.",
      "Bake cookies together — but one person is blindfolded.",
      "Create a playlist together and listen to it on a walk.",
      "Record a “podcast-style” voice note interviewing each other.",
      "Build a Lego set together.",
      "Create your own secret handshake.",
      "Make a vision board for your dream adventure.",
      "Each draw a treasure map and swap to follow it.",
      "Play “photo roulette” — take random silly pictures around town.",
      "Go on a $10 gift challenge at a dollar store.",
      "Write a short story together, alternating sentences.",
      "Make your own “inside joke” by the end of the night.",
      "Build paper airplanes and race them.",
      "Paint rocks and hide them around the city.",
      "Try karaoke, but only pick songs from before the year 2000.",
      "Put together a care package for a stranger.",
      "Make up a short dance routine together.",
      "Record a fake commercial for a random object near you.",
      "Create a superhero persona for each other."
    ],
    "Mirror Quests": [
      "Go to the last place you cried and make a happy memory there.",
      "Write letters to your future selves and exchange them.",
      "Visit a place that holds sentimental value to one of you.",
      "Each share a song that means a lot to you and explain why.",
      "Go to a quiet park and journal for 15 minutes, then share.",
      "Make a list of your top 5 values together.",
      "Go to your old school or neighborhood and tell stories.",
      "Share your favorite childhood memory in the place it happened.",
      "Create a “time capsule” with small objects and bury it.",
      "Each buy an object under $5 that represents your personality.",
      "Write a gratitude list of 10 things and share.",
      "Visit a local church/temple/mosque and talk about spirituality.",
      "Share your “biggest dream” while watching the stars.",
      "Recreate an old photo from your childhood.",
      "Write a list of fears and burn it (safely) together.",
      "Share your “first crush” story.",
      "Visit a cemetery and reflect on life lessons.",
      "Write an anonymous kind note and leave it in a public place.",
      "Take each other to a place that shaped who you are.",
      "Visit your favorite “escape spot” and explain why.",
      "Each share something you’ve never told anyone before.",
      "Go through each other’s “top 3” life lessons.",
      "Write a list of qualities you admire in each other.",
      "Go to a quiet library and each find a book that represents your current chapter in life.",
      "Talk about your biggest “turning point” in life while on a walk."
    ],
    "Bond Quests": [
      "Go to a discount store and buy full outfits for each other under $20.",
      "Sing loudly in a public space (bonus if it’s a duet).",
      "Ask a stranger to take a silly picture of you.",
      "Do a random act of kindness for a stranger.",
      "Eat at a restaurant where you don’t recognize anything on the menu.",
      "Take turns blindfolding each other while walking through a safe area.",
      "Do an open-mic night together (poetry, music, or comedy).",
      "Talk to someone new and ask them their life story.",
      "Spend an hour without your phones.",
      "Go to a crowded place and start a “mini dance circle.”",
      "Order food for each other without knowing what it is.",
      "Introduce yourselves to a stranger as a “fake backstory couple/friends.”",
      "Spend $5 each at a thrift shop and swap gifts.",
      "Ask a stranger to recommend their favorite local spot and go there.",
      "Have a “no talking” communication challenge for 10 minutes.",
      "Walk into a random event or meetup.",
      "Each share your top 3 fears, then try a small action against one.",
      "Pretend you’re tourists in your own city.",
      "Go to a fancy store and try on clothes you’d never buy.",
      "Do an improv challenge in a public park.",
      "Go to a fast-food drive-thru and order in a funny accent.",
      "Try a “silent dinner” where you can only communicate by notes.",
      "Swap phones and take random (safe) pictures on each other’s camera rolls.",
      "Go to your ex’s house (if safe) and write them a gratitude letter.",
      "End the night by writing one thing you appreciate about the other person."
    ],
  };
